name: CI/CD

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  build-and-test:
    if: github.event.pull_request.merged != true
    runs-on: ubuntu-latest

    steps:
      - name: Say hello
        run: echo Hello world

      - name: Create a text file
        run: echo "This file was generated during build-and-test." > build-output.txt

      - name: Upload text file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: build-output.txt

  update-jira:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Get Jira Issue Key
        id: extract
        run: |
          echo "JIRA_KEY=$(echo '${{ github.event.pull_request.title }}' | grep -o '[A-Z]\+-[0-9]\+')" >> $GITHUB_OUTPUT

      - name: Jira Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Change Jira issue to Done
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ steps.extract.outputs.JIRA_KEY }}
          transition: Done
          
      - name: Send message to Slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "Jira issue *${{ steps.extract.outputs.JIRA_KEY }}* has been closed successfully!"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
